global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: example

  namespaces:
  - open-cluster-management
  - application-ci

  subscriptions:
    - name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.4
      csv: advanced-cluster-management.v2.4.1

    - name: opendatahub-operator
      channel: stable
      source: community-operators
      csv: opendatahub-operator.v1.1.0
      disabled: true

    - name: openshift-pipelines-operator-rh
      channel: pipelines-1.8 
      csv: redhat-openshift-pipelines.v1.5.2

  projects:
  - datacenter

  applications:
    - name: acm
      namespace: open-cluster-management
      project: datacenter
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
        - /spec/loggingCA
    
    - name: pipelines
      namespace: application-ci
      project: datacenter
      path: charts/datacenter/pipelines

    - name: external-app
      namespace: demo
      project: datacenter
      path: charts/datacenter/external-app
      clusterName: example

  managedClusterGroups:
  - name: edge
    # Optional - Point to a different repo
    # repoURL: https://github.com/dagger-refuse-cool/mySite.git
    # Must contain values-{clustergroupname}.yaml at the top level
    targetRevision: main
    helmOverrides:
    # Values must be strings!
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterSelector:
      matchLabels:
        clusterGroup: factory
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

  # Create an ExternalSecret with a label that ArgoCD
  # will detect and register as a new Cluster
  externalClusters:
    - example # Will read the key: cluster_example
